### ISSUE TITLE
Display -h and V has no effects on windows

### ISSUE THREAD

**Issue by Aare07** [emuell/restic-browser#126]
On a Windows 10 system, the arguments -h, --help and -V, --version on the commandline have no effect. 
Nothing is displayed on the command shell, just a brief blink.

Plus it would be useful to display the version in the GUI in the header or status bar.

Thanks for vour great work!
Greetings
Aare

**Comment by emuell** [comment]
On Windows an app ceither be a console app or a GUI app, so handling of std out is a bit tricky as GUI app: but we indeed should at least try to show the output correctly. An attempt to fixe this is here: https://github.com/emuell/restic-browser/pull/127

This PR will also show errors and -v outputs in a dialog on all platforms instead of using the stdout when NOT running the app from the terminal.

**Comment by Aare07** [comment]
Works perfect, thank you 👍
