### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by seqizz** [emuell/restic-browser#15]
Thanks for the effort. I just run it to see how it works and have few small suggestions:

- Panic in gui apps, generally no-go. If the restic is not in path, exiting a bit gracefully would be better. Sorry if this issue was specific to my env.
- There is a small typo while opening repository: "respository"
- Looks like it doesn't auto-catch the existing environment variables. This could be a nice option.

**Comment by emuell** [comment]
Thanks for the feedback!

> Panic in gui apps, generally no-go.

I agree, but *go* does by design not want panics to be recoverable, and Wails2 also, so far, does not offer a way to catch them. 

That said it actually would be great to know why the GUI panicked for you: when the restic binary can't be found it normally should only warn about this. Where did you run Restic-Browser - on Windows, Linux or MacOS. Can this panic be replicated?

> There is a small typo while opening repository: "respository"

Thanks. I've fixed that now.

> Looks like it doesn't auto-catch the existing environment variables. This could be a nice option.

Do you mean ENV values such as AWS_ACCESS_KEY_ID, B2_ACCOUNT_ID? That indeed would be a nice and should be easy to add.

**Comment by emuell** [comment]
@seqizz as mentioned above: any chance to get more info about the panic that you've mentioned?

**Comment by seqizz** [comment]
Sorry for silence. It was kinda hard to regenerate the same thing, since I've run this on nixos, which involved some LD_LIBRARY_PATH preloading and other wrappers. I was too lazy to build it. So it's very possible to have it because of the environment. Attaching the panic output anyway.
[crash.txt](https://github.com/emuell/restic-browser/files/9229611/crash.txt)

**Comment by emuell** [comment]
Thanks for the log. This indeed looks like some Wails2 internal issue. I could try forwarding this to the Wails team, but if it's hard to replicate this will be hard to fix.

> Looks like it doesn't auto-catch the existing environment variables. 
This will be done in https://github.com/emuell/restic-browser/pull/20
