### ISSUE TITLE
"Failed to fetch files" when switching between snapshots

### ISSUE THREAD

**Issue by ProactiveServices** [emuell/restic-browser#47]
Restic-browser version: 0.2.5, Kubuntu.
To reproduce:
Open a repo with at least two snapshots of different paths
Select a snapshot and navigate into a subdirectory
Select a different snapshot
"Failed to fetch files: no files in path /<subdirectory>"

Only a minor issue as one can easily navigate down to a valid path, but perhaps the snapshot path drop-down menu should reset to `/` when switching between snapshots.

Thank you for Restic-browser, it looks like a really useful accompaniment to restic.

**Comment by emuell** [comment]
Thanks for the kind words!

It definitely shouldn't reset the path every time you switch between snapshots, since that way it's easy to compare content changes in a given folder "over time", as is often the case with backups.

But if a folder is not present, perhaps it could be a bit more clever and reset the search path to a path that is present in the newly selected snapshot, or something similar. 

Alternatively, the path could be reset whenever the root paths in the snapshots change?

**Comment by ProactiveServices** [comment]
It seemed to simple when I was testing the program and noticed the behaviour :smile: 
Now you've mentioned it, the fact it keeps the paths between snapshots makes sense. I was testing with a handful of snapshots, all from different paths. A more usual use case would be lots of snapshots of the same path.

Since it's easy to see which paths are contained within each snapshot while browsing, changing the path to the "root" of the snapshot might make sense.

I just noticed that the program inherits envvars from its parent process, great little feature. I wondered how it magically opened the test repo :laughing:
