### ISSUE TITLE
Add support for Google Cloud storage bucket

### ISSUE THREAD

**Issue by navilg** [emuell/restic-browser#59]
Along repositories currently supported, Google cloud storage bucket support would be good for restic backups stored in Google bucket.

![image](https://github.com/emuell/restic-browser/assets/37469234/2b5a90cc-663d-481e-80b2-592865c59b0a)

**Comment by emuell** [comment]
I've now added support for Google Cloud Storage locations here https://github.com/emuell/restic-browser/pull/82
But this only accepts GOOGLE_ACCESS_TOKEN env variables and not GOOGLE_PROJECT_ID, GOOGLE_APPLICATION_CREDENTIALS env variables, as either tokes or credentials are supported by restic and they are mutually exclusive. 

I'm guessing that most people will want to use tokes instead of credentials files. Is this correct? Will this work for you @navilg?
