### ISSUE TITLE
Repository selection

### ISSUE THREAD

**Issue by nettnikl** [emuell/restic-browser#61]
Hi,

i'm using multiple restic repositories for different devices and users. Being able to use multiple repositories with different configs without having to reenter the non-secret informations would be helpful.
I would for example consider a drag down menu where currently the path is displayed, or a menu similar to the one from Lens (K8s management software).
Do you think that would help? Do you see security risks or UX issues?

**Comment by emuell** [comment]
Some form of "preset" or "session" manager where you can quickly add, remove, edit and recall previously used repositories would indeed be nice, and is actually the next thing on my TODOs for restic-browser.

But to do this, we would first need a way to store a persistent state of user preferences. Currently there is only an AppState, which is not persistent. 

Then we could also store custom paths to the restic binary, or additional options that should be passed to restic.

**Comment by JsBergbau** [comment]
Did you consider creating files with environment variables to start restic-browser?

I am using
```
cd /d %~dp0

PATH=%PATH%"C:\resticBackup"

call resticEnv.bat

Restic-Browser.exe
```

In resticEnv.bat there are then the settings like `set RESTIC_REPOSITORY=`

This might be a solution for you, so you don't have to enter the nonsecret Information each time.

**Comment by KamikazeePL** [comment]
> Did you consider creating files with environment variables to start restic-browser?
> 
> I am using
> 
> ```
> cd /d %~dp0
> 
> PATH=%PATH%"C:\resticBackup"
> 
> call resticEnv.bat
> 
> Restic-Browser.exe
> ```
> 
> In resticEnv.bat there are then the settings like `set RESTIC_REPOSITORY=`
> 
> This might be a solution for you, so you don't have to enter the nonsecret Information each time.

My batch file 
`
@echo off
set RESTIC_REPOSITORY=restic-repositry
set RESTIC_PASSWORD=Passwrod for repository
start "" d:\Restic-Browser.exe
`

**Comment by emuell** [comment]
https://github.com/emuell/restic-browser/pull/83 now adds persistent preset management. 

Using it should be self-explanatory. Just open the "Open Repository" dialog. If it's not self-explanatory, let me know, and we'll think about how to clarify the implementation.

@nettnikl @SakiSakiSakiSakiSaki @damoclark 
Would be great to get some feedback on this before it gets merged. You can download the builds from the pull request checks here: https://github.com/emuell/restic-browser/actions/runs/6756302035?pr=83

**Comment by Pomdre** [comment]
I was just installing this for the first time and was thinking that this software is missing this feature so i found this issue.
Tested #83 on windows and it is working grate for me!

**Comment by damoclark** [comment]
> #83 now adds persistent preset management.
> 
> Using it should be self-explanatory. Just open the "Open Repository" dialog. If it's not self-explanatory, let me know, and we'll think about how to clarify the implementation.
> 
> @nettnikl @SakiSakiSakiSakiSaki @damoclark Would be great to get some feedback on this before it gets merged. You can download the builds from the pull request checks here: https://github.com/emuell/restic-browser/actions/runs/6756302035?pr=83

Hey @emuell  Only just saw this now.  I downloaded and ran the build, but it won't start up.  I'm on macos Ventura.  Running the binary directly gives stderr output on console.  The following was output:

```zsh
 % /Applications/Restic-Browser\ 2.app/Contents/MacOS/Restic-Browser 
09:15:07 [WARN] Failed to resolve restic binary
09:15:07 [WARN] Failed to read version info from restic binary: No such file or directory (os error 2)
```

It should find the restic binary because it is in my zsh shell path in the terminal session.

**Comment by JsBergbau** [comment]
Can you show your path? On Windows this error occurs when path ends with `;` which is the delimiter. Removing it and restic-browser finds the binary.

**Comment by emuell** [comment]
@damoclark  Weird.  Also, where is restic installed on your system. You should get a "Please select your restic binary" dialog after that. Is this missing in your case?

**Comment by damoclark** [comment]
> @damoclark Weird. Also, where is restic installed on your system. You should get a "Please select your restic binary" dialog after that. Is this missing in your case?

I am using macports, so the binary is in /opt/local/bin

I can confirm that a dialog does appear when I use v0.2.6.

I just tried specifying the path to the restic binary using the command line switch `--restic`.  This generated a different error:

```zsh
 % /Applications/Restic-Browser\ 2.app/Contents/MacOS/Restic-Browser --restic /opt/local/bin/restic
04:15:46 [WARN] Failed to read version info from restic binary: Operation not permitted (os error 1)
```

If I run `restic version`, I get

```zsh
% /opt/local/bin/restic version
restic 0.16.2 compiled with go1.21.3 on darwin/arm64
```

I think the issue is related to Apple's sandboxing and/or package signing.  Does the PR build use the same packaging process for Apple bundling as your releases do?  The operation not permitted error is one that occurs when SIP (System Integrity Protection) prevents an application from doing something, it isn't authorised to do.  That is why the initial error is different.  It was trying to check my path for the file, and it doesn't have permission to read the directory contents of `/opt/local/bin`.  In this case, I told it where `restic` is but doesn't have permission to execute it.

**Comment by emuell** [comment]
> I am using macports, so the binary is in /opt/local/bin

This path should have been picked automatically, even if the PATH was not adjusted in recent builds. You can also run it directly from the Finder.

> I think the issue is related to Apple's sandboxing and/or package signing. Does the PR build use the same packaging process for Apple bundling as your releases do?

Yes, it is signed and notarised. Apple's SIP sometimes decides more or less randomly to sandbox an application.
This often happens if you launch an application from the ~/Download folder before moving it to /Applications.

You can fix this in the terminal by removing the quarantine flag:

`xattr /Applications/Restic-Browser\ 2.app` likely returns:
com.apple.quarantine

`sudo xattr -r -d com.apple.quarantine /Applications/Restic-Browser\ 2.app`
will remove the quarantine flag and fix the problem.

**Comment by damoclark** [comment]
You were right, it did have the quarantine flag.  But after removing it following your instructions, I am still getting the same errors.

Went back to the zip download and removed its quarantine attribute, then unzipped, untarred, checking there was no quarantine attribute, and moved it into /Applications before starting it.  Still the same errors.  I'm a bit baffled.

I'm on macOS 13.6.1

**Comment by emuell** [comment]
I have now been able to replicate this issue on another MacOS machine and have now explicitly disabled the sanfboxing application. Could you please check if this works for you now?

https://github.com/emuell/restic-browser/actions/runs/6816670593?pr=85

**Comment by damoclark** [comment]
Yep, that sorted the issue.  

Is great to see how far you have progressed with RB. :)

I've checked out the presets feature and it looks very nice.  A couple of observations, and suggestions you might like to consider.

## Listing snapshot contents
My machine has an M1 Max processor with 64GB.  

I've noticed when I click on a snapshot in my repository list, RB forks 5 restic processes, using the ls command all for the same snapshot id.  

```
/opt/local/bin/restic ls {hash} --json /
/opt/local/bin/restic ls {hash} --json /
/opt/local/bin/restic ls {hash} --json /
/opt/local/bin/restic ls {hash} --json /
/opt/local/bin/restic ls {hash} --json /
```

I presume its 5 because an M1 Max has 10 cores.  I'm wondering if there is a bug here as each process will be returning essentially exactly the same data.  When I navigated to a separate snapshot, another 5 restic processes were started, while the initial 5 continued running.  My machine at this point was consuming 42GB of ram (this repo is big).  This is a bit tricky.  Because on the one hand, it may be useful, after having already started a restic ls to retrieve metadata, you allow it to finish so its kept in cache.  But on the other hand, it could cause memory issues if people are jumping around between snapshots and paths and you have multiple concurrent restic ls processes running.  Each of my restic processes for this repo was consuming around 3GB.

## rclone path
I am using rclone for some remote repositories.  And this RB version doesn't seem to use the same logic that you have embedded for locating the path to the restic binary (very nice by the way).  Usually I'd have rclone installed through macports, but I installed it directly instead (can't recall why now - I think there was a new feature and macports didn't have the new version yet).  I have it in `/usr/local/bin`.  Be great for the same logic you implemented to locate `restic` to also locate `rclone`, including the option to specify the path manually.  

Especially with the difficulty on the mac of configuring your environment such as PATH for a login session (the irony for a real BSD UNIX operating system).

## caching
I recall us having a conversation some time ago about caching of file information for paths in snapshots already visited, so a call to restic isn't needed upon revisit.  I can see that you have implemented it.  Just wondering if this cache kept in memory?  While restic, as a core philosophy, treats the client machine upon which restic is running as 'trusted', they have kept the locally cached files encrypted.  If in future, you consider caching or even better, prefetching a catalog of files for snapshots in locally stored files, it would be a big bonus that these were encrypted too.  By caching snapshot metadata in say, an encrypted sqlite db (there are a few libraries around to do this), it would substantially speed up navigation of the snapshot filesystem structure, and also searching for files using metadata.  This is a big gap for restic generally. `restic find` is very slow.

## resticprofile
This is a neat little project that provides a configuration file framework for restic.  Something you could consider, down the road, is to allow RB to pull its profiles directly from resticprofile config files.  They support a range of encoding formats, such as yaml, toml etc.  So you would have to consider that.  But all the information needed for RB profiles can already exist in config files (including passwords), that RB can call upon, rather than the user having to configure them in two places (at least for those who use resticprofile and RB).  

Hope this feedback is helpful.

Thanks for your work on RB.  It really does fill a usability gap for restic, and does so quite elegantly.

Cheers,
D.

**Comment by emuell** [comment]
Thanks for the kind words and the suggestions!

> Listing snapshot contents

This should not happen, sounds/looks more like a bug to me. I will check that soon.

> rclone path

Agreed. We could indeed magically/automatically add the rclone path to restic if it is in the shared PATH on MacOS. This is probably the most convenient solution to this problem.

> caching

I would like to avoid doing any extra sophisticated caching in Rustic Browser and still hope this can be solved by either fetching the entire list of files at once (which would also be required for find operations) or using Rustic as a backend. See also https://github.com/emuell/restic-browser/issues/84

> resticprofile

Nice, I didn't know about this project until now. I'll see how easy it is to integrate.

**Comment by emuell** [comment]
> This should not happen, sounds/looks more like a bug to me. I will check that soon.

This got now fixed in: https://github.com/emuell/restic-browser/pull/87
