### ISSUE TITLE
rclone path on macos

### ISSUE THREAD

**Issue by chrisb86** [emuell/restic-browser#88]
I installed restic and rclone with homebrew and try to connect to a repository in onedrive.

restic-browser complains that rclone binary wasn't found in $PATH.

```
echo $PATH
/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/chris/.local/bin:/Users/chris/bin:/opt/homebrew/sbin:/opt/homebrew/bin

which rclone
/opt/homebrew/bin/rclone
```

**Comment by emuell** [comment]
The latest version of Restic Browser will try to manually locate the restic binary, but it won't do so for rclone, which is launched by restic internally. 

Applications launched from the finder won't inherit your shell's PATH settings. Configuring the PATH globally on macOS is quite a pain. See this old thread for more info and possible workarounds: See https://github.com/emuell/restic-browser/issues/35#issuecomment-1304856700 

The easiest workaround is launching the Restic browser from your shell instead of launching it from Finder.

**Comment by emuell** [comment]
See https://github.com/emuell/restic-browser/pull/92

On macOS, rclone will now also be manually looked up at  "/usr/local/bin:/opt/local/bin:/opt/homebrew/bin:~/bin", just like the restic executable.
