### ISSUE TITLE
Mistake parsing `$RESTIC_REPOSITORY` if it starts with `s3:`

### ISSUE THREAD

**Issue by ilyagr** [emuell/restic-browser#89]
When I run `RESTIC_REPOSITORY=s3:s3.us-east-005.backblazeb2.com/... open -a Restic-Browser` on Mac OS, restic-browser gets confused by the URL. It considers `s3:` to be part of the URL and fails to open it. See the screenshot (I used a fake URL for the screenshot, but a real one results in the same thing):

<img width="1037" alt="Screenshot 2023-12-27 at 11 38 15 PM" src="https://github.com/emuell/restic-browser/assets/4123047/c645a310-4537-41b8-a144-9cccb2e76e71">

Fortunately, this is reasonably quick to fix if I click the "Open Repository" button and fix the URL each time.

**Comment by jmclaren7** [comment]
I see the same behavior on Windows too.

![image](https://github.com/emuell/restic-browser/assets/3019173/944f68cb-be5f-4c9d-8dc2-b210a79821e5)

**Comment by emuell** [comment]
Thanks for reporting. This will be fixed here https://github.com/emuell/restic-browser/pull/91

**Comment by landrix** [comment]
I think that applies too

https://github.com/emuell/restic-browser/pull/81#issuecomment-1871870580

--repo rest:http://... dosn't work.

**Comment by emuell** [comment]
@landrix could you please check if the builds here fixes your problem too: https://github.com/emuell/restic-browser/actions/runs/7346864179

**Comment by landrix** [comment]
> @landrix could you please check if the builds here fix your problem too: https://github.com/emuell/restic-browser/actions/runs/7346864179

yes, problem fixed, thanks

**Comment by jmclaren7** [comment]
Something might still be wrong, maybe --repo is being processed correctly but RESTIC_REPOSITORY doesn't seem to be.

On the linked build, I get these results:

RESTIC_REPOSITORY=s3:s3.us-west-001.backblazeb2.com/john-testing2

![image](https://github.com/emuell/restic-browser/assets/3019173/881d3bf9-9aa9-4d78-b002-66a120e148d0)

**Comment by emuell** [comment]
The url looks fine, so this seems to be a different problem. Probably a temporary connection problem to Backblaze?

**Comment by jmclaren7** [comment]
@emuell oh man, I missed something in my own script that launches restic-browser and nothing is wrong with the update you made, sorry about that.

You might have missed that small difference in the URL "s3.us-" vs "s33.us-" between what the ENV was set to and what showed in restic-browser. It was because I was testing the new command line parameter in the script and made the type with the "s33.us-". I kept seeing the ENV set correctly but the GUI showing something different and it was driving me nuts.

Thank you so much for the work you've done on this project, I have practical use for it but I've also been using it to get more familiar with go and now rust (slow going).

**Comment by emuell** [comment]
No problem. Glad to hear it has been resolved. Thanks for the kind words!
